#ifndef __CONFIG_TYPES_H__
#define __CONFIG_TYPES_H__

/* This file is normally generated by libogg's configure/cmake. It is committed
   here so the bundled libogg builds without an external libogg-dev package.
   All supported toolchains (MSVC 2015+, g++, clang) provide <stdint.h>. */

#define INCLUDE_INTTYPES_H 1
#define INCLUDE_STDINT_H 1
#define INCLUDE_SYS_TYPES_H 1

#if INCLUDE_INTTYPES_H
#  include <inttypes.h>
#endif
#if INCLUDE_STDINT_H
#  include <stdint.h>
#endif
#if INCLUDE_SYS_TYPES_H
#  include <sys/types.h>
#endif

typedef int16_t ogg_int16_t;
typedef uint16_t ogg_uint16_t;
typedef int32_t ogg_int32_t;
typedef uint32_t ogg_uint32_t;
typedef int64_t ogg_int64_t;
typedef uint64_t ogg_uint64_t;

#endif
